### ISSUE TITLE
Unrecognized Config Version

### ISSUE THREAD

**Issue by ezr0** [libvibrant/vibrantLinux#37]
I am getting the above error when i try to launch. Says to delete ~/.config/vibrantlinux/vibrantLinux.internal but that doesnt exist.

Running PopOS.

**Comment by Scrumplex** [comment]
I have released a new version. Please update and check if it works now

**Comment by ezr0** [comment]
Hi thanks for the quick reply, unfortunately i am on the latest version according to flatpack and i'm still getting the error. 

Running it via terminal states "Failed to load on module":

- appmenu-gtk-module
- canberra-gtk-module

With the same unrecognized config window

**Comment by Scrumplex** [comment]
Sorry, seems like I forgot to actually publish the Flatpak. It should be available by now

**Comment by ezr0** [comment]
Thank you! works perfectly :)

**Comment by Jota-veh** [comment]
hey man,
just passing by to report a problem and a solution i found, so i'll not report this.

If your "vibrant" keeps resetting your config file, there is a solution:

1. Configure all the programs and windows titles you want to use.
2. after that, change the proprieties of the config file to "read only".
3. when you need to do more changes, just change the config file to "read and write " again, then make your changes, and then go for "read only" again.

thanks for this amazing app!

**Comment by Scrumplex** [comment]
@Jota-veh is this actually a problem? Like randomly resetting configs? I sadly don't use this app much, as I basically never use ann X11 session.

**Comment by Jota-veh** [comment]
yes man, idk if this is still happening with this new version, because before you fixed that "set vibrance only when..." problem, this was not happening, and now, i'm using this method as a solution.
btw, I use this app to only allow colors in productive programs, and grayscale on distractions ones. 


but I'll use this app like before, with original configs proprieties, beause you updated again, and report to you only if this is still hapenning.

**Comment by Jota-veh** [comment]
Yes, man, it is still happening.
But if anyone else is reporting this, maybe it's only with me, you know? And i'm good.
